#***************************************************************************
#*   NetGuard General Accounting Module Makefile                           *
#*                                                                         *
#*   Copyright (c) 2011 Daniel Rudolph <daniel at net-guard net>           *
#*                                                                         *
#*                                                                         *
#*   This program is released under a dual license.                        *
#*   GNU General Public License for open source and educational use and    *
#*   the Net-Guard Professional License for commercial use.                *
#*   Details: http://www.net-guard.net/licence                             *
#*                                                                         *
#*   For open source and educational use:                                  *
#*   This program is free software; you can redistribute it and/or modify  *
#*   it under the terms of the GNU General Public License as published by  *
#*   the Free Software Foundation; either version 2 of the License, or     *
#*   (at your option) any later version.                                   *
#*                                                                         *
#*   This program is distributed in the hope that it will be useful,       *
#*   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
#*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
#*   GNU General Public License for more details.                          *
#*                                                                         *
#*   You should have received a copy of the GNU General Public License     *
#*   along with this program; if not, write to the                         *
#*   Free Software Foundation, Inc.,                                       *
#*   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
#*                                                                         *
#*   For commercal use:                                                    *
#*   visit http://www.net-guard.net for details if you need a commercal    *
#*   license or not. All conditions are listed here:                       *
#*                 http://www.net-guard.net/licence                        *
#*                                                                         *
#*   If you are unsure what licence you can use you should take            *
#*   the Net-Guard Professional License.                                   *
#*                                                                         *
#***************************************************************************

############################################################################
LIBNAME=general_accounting
#MODULENAME=
############################################################################
NGDIR ?= ../../
include $(NGDIR)/mk/Makeconf

include $(NGDIR)/mk/MakeModule

